### PR TITLE
Update readme to clarify code layout and initial config

### PR DESCRIPTION
**Pull request by tim-du**
## Status
**READY**

## Migrations
NO

## Description
Update readme

## Notes
Changes based on conversation here: https://github.com/airmap/platform-sdk/issues/186

## Impacted Areas in AirMap Platform SDK
List general components of the SDK that this PR will affect:

* README.md

### CODE REVIEW

**Review by keith-bennett-airmap — APPROVED** [review]
This looks fine by me.

I don't know enough about `platform-sdk` to judge correctness of the changes. @remster

**Review by remster — APPROVED** [review]

**Comment by remster** [comment]
In case you still haven't got access to azure, the failing CI says:
```
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-c++11-narrowing'
[ 59%] Building CXX object src/airmap/CMakeFiles/airmap-client.dir/util/scenario_simulator.cpp.o
[ 60%] Building CXX object src/airmap/CMakeFiles/airmap-client.dir/util/telemetry_simulator.cpp.o
[ 61%] Building CXX object src/airmap/CMakeFiles/airmap-client.dir/version.cpp.o
/usr/src/app/build/src/airmap/version.cpp: In static member function 'static const airmap::Version& airmap::Version::current()':
/usr/src/app/build/src/airmap/version.cpp:7:9: error: expected primary-expression before ',' token
         ,
         ^
At global scope:
cc1plus: warning: unrecognized command line option '-Wno-c++11-narrowing'
src/airmap/CMakeFiles/airmap-client.dir/build.make:1057: recipe for target 'src/airmap/CMakeFiles/airmap-client.dir/version.cpp.o' failed
make[2]: *** [src/airmap/CMakeFiles/airmap-client.dir/version.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:1065: recipe for target 'src/airmap/CMakeFiles/airmap-client.dir/all' failed
make[1]: *** [src/airmap/CMakeFiles/airmap-client.dir/all] Error 2
Makefile:182: recipe for target 'all' failed
make: *** [all] Error 2
The command '/bin/sh -c make -j "$(nproc)"' returned a non-zero code: 2
##[error]The command '/bin/sh -c make -j "$(nproc)"' returned a non-zero code: 2
##[error]The process '/usr/bin/docker' failed with exit code 2

```

**Comment by keith-bennett-airmap** [comment]
@remster that's not a change he made. That's a problem with the `2.0` tag being the tag that git picks up. It's not parsed correctly by the cmake version template because it doesn't have the bugfix version part

**Comment by remster** [comment]
> @remster that's not a change he made. That's a problem with the `2.0` tag being the tag that git picks up. It's not parsed correctly by the cmake version template because it doesn't have the bugfix version part

Yes I know - i just thought he couldn't see into Azure and didn't know why the CI fails. Do you have "the bugfix version part" some other place?

**Comment by keith-bennett-airmap** [comment]
> i just thought he couldn't see into Azure and didn't know why the CI fails

Ahh good point

> Do you have "the bugfix version part" some other place?

I do not. But it can be fixed around [here](https://github.com/airmap/platform-sdk/blob/554038630566e9f69bc8a7a4b96787a565cb5735/CMakeLists.txt#L9) by parsing version into a semver, adding a check for bugfix version -- if it's empty then set it to zero and add it to the semver output from `git_describe`

**Pull request merged**
